apiVersion: v1
kind: Endpoints
metadata:
  name: kplabs-service
#spec:
#  ports:
#  - port: 8080
#    targetPort: 80

subsets:
  - addresses:
      - ip: 192.168.33.243 
    ports:
      - port: 80 

