apiVersion: v1
kind: Pod
metadata: 
  name: kplabs-pod-test
spec:
  containers:
  - name: kplabs-container
    image: nginx
    resources:
      limits:
        memory: "512Mi"
        cpu: "1"
      requests:
        memory: "64Mi"
        cpu: "0.5"
#      limits:
#        memory: "128Mi" //12GB RAM is assigned
#        cpu: "1"
